### PR TITLE
data ingestion flow

### PR DESCRIPTION
**Pull request by bishw123**

### CODE REVIEW

**Comment by pratibhaparhar** [comment]
Do some changes

**Review by NishaneLPN — COMMENTED** [review]
Thnaks

**Review by Kanchan-Nazare — COMMENTED** [review]
Done

**Review by Mayur-111 — APPROVED** [review]

**Review by Kanchan-Nazare — APPROVED** [review]
Done

**Review by NishaneLPN — APPROVED** [review]

**Pull request merged**
